"""add property borrower fields and watchlist

Revision ID: 0824c9c48edc
Revises: 7b5125a8d967
Create Date: 2026-03-11 15:46:12.091627

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0824c9c48edc'
down_revision: Union[str, None] = '7b5125a8d967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('alert_on_delinquency_change', sa.Boolean(), nullable=False),
    sa.Column('alert_on_servicer_advance', sa.Boolean(), nullable=False),
    sa.Column('alert_on_maturity_within_months', sa.Integer(), nullable=True),
    sa.Column('last_checked_filing_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['last_checked_filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('loans', sa.Column('property_name', sa.String(length=500), nullable=True))
    op.add_column('loans', sa.Column('property_city', sa.String(length=200), nullable=True))
    op.add_column('loans', sa.Column('property_state', sa.String(length=2), nullable=True))
    op.add_column('loans', sa.Column('borrower_name', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_loans_borrower_name'), 'loans', ['borrower_name'], unique=False)
    op.create_index(op.f('ix_loans_property_city'), 'loans', ['property_city'], unique=False)
    op.create_index(op.f('ix_loans_property_name'), 'loans', ['property_name'], unique=False)
    op.create_index(op.f('ix_loans_property_state'), 'loans', ['property_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_property_state'), table_name='loans')
    op.drop_index(op.f('ix_loans_property_name'), table_name='loans')
    op.drop_index(op.f('ix_loans_property_city'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_name'), table_name='loans')
    op.drop_column('loans', 'borrower_name')
    op.drop_column('loans', 'property_state')
    op.drop_column('loans', 'property_city')
    op.drop_column('loans', 'property_name')
    op.drop_table('watchlist_items')
    # ### end Alembic commands ###
