"""add_credit_metrics_and_loan_flags

Revision ID: 3b5c128f09fd
Revises: 55bd7649b515
Create Date: 2026-03-12 13:08:54.547373

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b5c128f09fd'
down_revision: Union[str, None] = '55bd7649b515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_snapshots', sa.Column('dscr_noi', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('loan_snapshots', sa.Column('dscr_ncf', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('loan_snapshots', sa.Column('noi', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('loan_snapshots', sa.Column('ncf', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('loan_snapshots', sa.Column('occupancy', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('loan_snapshots', sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('loan_snapshots', sa.Column('operating_expenses', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('loan_snapshots', sa.Column('debt_service', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('loan_snapshots', sa.Column('appraised_value', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column(
        'loan_snapshots',
        sa.Column('dscr_noi_at_securitization', sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        'loan_snapshots',
        sa.Column('dscr_ncf_at_securitization', sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        'loan_snapshots',
        sa.Column('noi_at_securitization', sa.Numeric(precision=20, scale=2), nullable=True),
    )
    op.add_column(
        'loan_snapshots',
        sa.Column('ncf_at_securitization', sa.Numeric(precision=20, scale=2), nullable=True),
    )
    op.add_column(
        'loan_snapshots',
        sa.Column('occupancy_at_securitization', sa.Numeric(precision=5, scale=4), nullable=True),
    )
    op.add_column(
        'loan_snapshots',
        sa.Column('appraised_value_at_securitization', sa.Numeric(precision=20, scale=2), nullable=True),
    )
    op.add_column('loans', sa.Column('interest_only_indicator', sa.Boolean(), nullable=True))
    op.add_column('loans', sa.Column('balloon_indicator', sa.Boolean(), nullable=True))
    op.add_column('loans', sa.Column('lien_position', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'lien_position')
    op.drop_column('loans', 'balloon_indicator')
    op.drop_column('loans', 'interest_only_indicator')
    op.drop_column('loan_snapshots', 'appraised_value_at_securitization')
    op.drop_column('loan_snapshots', 'occupancy_at_securitization')
    op.drop_column('loan_snapshots', 'ncf_at_securitization')
    op.drop_column('loan_snapshots', 'noi_at_securitization')
    op.drop_column('loan_snapshots', 'dscr_ncf_at_securitization')
    op.drop_column('loan_snapshots', 'dscr_noi_at_securitization')
    op.drop_column('loan_snapshots', 'appraised_value')
    op.drop_column('loan_snapshots', 'debt_service')
    op.drop_column('loan_snapshots', 'operating_expenses')
    op.drop_column('loan_snapshots', 'revenue')
    op.drop_column('loan_snapshots', 'occupancy')
    op.drop_column('loan_snapshots', 'ncf')
    op.drop_column('loan_snapshots', 'noi')
    op.drop_column('loan_snapshots', 'dscr_ncf')
    op.drop_column('loan_snapshots', 'dscr_noi')
    # ### end Alembic commands ###
