"""add unique constraints for loans and snapshots

Revision ID: 55bd7649b515
Revises: e0737ca41936
Create Date: 2026-03-12 02:21:34.643081

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '55bd7649b515'
down_revision: Union[str, None] = 'e0737ca41936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_snapshots_loan_filing', 'loan_snapshots', ['loan_id', 'filing_id'], unique=True)
    op.create_index('uq_loans_deal_prospectus', 'loans', ['deal_id', 'prospectus_loan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_loans_deal_prospectus', table_name='loans')
    op.drop_index('uq_snapshots_loan_filing', table_name='loan_snapshots')
    # ### end Alembic commands ###
