"""initial tables

Revision ID: 7b5125a8d967
Revises: 
Create Date: 2026-03-10 16:39:16.733880

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b5125a8d967'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cik_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_ticker', sa.String(length=100), nullable=False),
    sa.Column('issuer_shelf', sa.String(length=50), nullable=False),
    sa.Column('trust_name', sa.String(length=500), nullable=False),
    sa.Column('depositor_name', sa.String(length=300), nullable=False),
    sa.Column('depositor_cik', sa.String(length=20), nullable=False),
    sa.Column('trust_cik', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cik_mappings_deal_ticker', 'cik_mappings', ['deal_ticker'], unique=False)
    op.create_index('ix_cik_mappings_depositor_cik', 'cik_mappings', ['depositor_cik'], unique=False)
    op.create_index('ix_cik_mappings_issuer_shelf', 'cik_mappings', ['issuer_shelf'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('trust_name', sa.String(length=500), nullable=False),
    sa.Column('depositor_cik', sa.String(length=20), nullable=False),
    sa.Column('trust_cik', sa.String(length=20), nullable=True),
    sa.Column('issuer_shelf', sa.String(length=50), nullable=False),
    sa.Column('issuance_year', sa.Integer(), nullable=False),
    sa.Column('original_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('loan_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_ticker'), 'deals', ['ticker'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('reporting_period_start', sa.Date(), nullable=True),
    sa.Column('reporting_period_end', sa.Date(), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('exhibit_url', sa.Text(), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('prospectus_loan_id', sa.String(length=100), nullable=False),
    sa.Column('asset_number', sa.Integer(), nullable=False),
    sa.Column('originator_name', sa.String(length=300), nullable=True),
    sa.Column('original_loan_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('origination_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('original_term_months', sa.Integer(), nullable=True),
    sa.Column('original_amortization_term_months', sa.Integer(), nullable=True),
    sa.Column('original_interest_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period_begin_date', sa.Date(), nullable=False),
    sa.Column('reporting_period_end_date', sa.Date(), nullable=False),
    sa.Column('beginning_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ending_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('current_interest_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('scheduled_interest_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('scheduled_principal_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_interest_collected', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_principal_collected', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_other_collected', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('servicer_advanced_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delinquency_status', sa.String(length=20), nullable=True),
    sa.Column('interest_paid_through_date', sa.Date(), nullable=True),
    sa.Column('next_payment_amount_due', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_snapshots')
    op.drop_table('loans')
    op.drop_table('filings')
    op.drop_index(op.f('ix_deals_ticker'), table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_cik_mappings_issuer_shelf', table_name='cik_mappings')
    op.drop_index('ix_cik_mappings_depositor_cik', table_name='cik_mappings')
    op.drop_index('ix_cik_mappings_deal_ticker', table_name='cik_mappings')
    op.drop_table('cik_mappings')
    # ### end Alembic commands ###
